global:
  scrape_interval:     15s

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot 애플리케이션 모니터링
  - job_name: 'dummytalk-be'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      # Docker Compose 네트워크 내의 Spring Boot 서비스 이름과 포트 사용
      - targets: ['spring-app:8080']